version: "3"
services:
  db:
    image: postgres:latest
    network_mode: bridge
    container_name: spring_postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: spring-docker
    network_mode: bridge
    container_name: springbootapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
volumes:
  postgres-data: